name: Deploy Automation

on:
  push:
    branches:
      - main
      - dev
      - sandbox
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Installing sfdx cli
        run: sudo npm install @salesforce/cli --global

      - name: Reading Config File
        run: |
          ORG_ALIAS=$(grep ORG_ALIAS= config.txt | cut -d '=' -f2)
          ORG_USERNAME=$(grep ORG_USERNAME= config.txt | cut -d '=' -f2)
          
          echo "ORG_ALIAS=$ORG_ALIAS" >> $GITHUB_ENV
          echo "ORG_USERNAME=$ORG_USERNAME" >> $GITHUB_ENV

      - name: Setting Secrets for Org
        run: |
          CLIENT_ID_SECRET="${ORG_ALIAS}_CLIENT_ID"
          SERVER_KEY_SECRET="${ORG_ALIAS}_SERVER_KEY"
          
          echo "CLIENT_ID_SECRET=$CLIENT_ID_SECRET" >> $GITHUB_ENV
          echo "SERVER_KEY_SECRET=$SERVER_KEY_SECRET" >> $GITHUB_ENV

      - name: Generate package.xml for all metadata types
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > manifest/package.xml
          echo '<Package xmlns="http://soap.sforce.com/2006/04/metadata">' >> manifest/package.xml

          declare -A metadataMap=(
            ["classes"]="ApexClass"
            ["triggers"]="ApexTrigger"
            ["pages"]="ApexPage"
            ["components"]="AuraDefinitionBundle"
            ["lwc"]="LightningComponentBundle"
            ["objects"]="CustomObject"
            ["layouts"]="Layout"
            ["tabs"]="CustomTab"
          )

          for directory in "${!metadataMap[@]}"; do
            METADATA_TYPE="${metadataMap[$directory]}"
            
            # Find modified or added files in each directory
            MODIFIED_FILES=$(git diff --name-only --diff-filter=AM HEAD^ HEAD -- "$directory/*")
            
            if [ -n "$MODIFIED_FILES" ]; then
              echo "  <types>" >> manifest/package.xml
              for FILE in $MODIFIED_FILES; do
                # Remove file extensions for metadata members
                FILE_NAME=$(basename "$FILE" | sed 's/\.[^.]*$//')
                echo "    <members>$FILE_NAME</members>" >> manifest/package.xml
              done
              echo "    <name>$METADATA_TYPE</name>" >> manifest/package.xml
              echo "  </types>" >> manifest/package.xml
            fi
          done

          echo '  <version>61.0</version>' >> manifest/package.xml
          echo '</Package>' >> manifest/package.xml

          cat manifest/package.xml

      - name: Auth to Salesforce Org
        run: |
            echo -e "${{ secrets[env.SERVER_KEY_SECRET] }}" > ./server.key
            sf org login jwt --client-id ${{ secrets[env.CLIENT_ID_SECRET] }} \
              --jwt-key-file server.key \
              --username ${{ env.ORG_USERNAME }} \
              --alias ${{ env.ORG_ALIAS }} --set-default

      - name: Deploy modified files
        if: success() && steps.deploy.outputs.MODIFIED_FILES != ''
        run: |
          sf project deploy start --manifest manifest/package.xml \
            --target-org ${{ env.ORG_ALIAS }} \
            --test-level RunLocalTests -c > deployResult.txt
          cat deployResult.txt
